# font
font_size        11.0
cursor_shape     block
font_family      family='JetBrainsMono Nerd Font'
bold_font        auto
italic_font      auto
bold_italic_font auto

# URL
url_style        curly
detect_urls      yes

# Foreground / Background
background_opacity 0.8
window_padding_width 20 30
dynamic_background_opacity yes

#crusor
cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 0
shell_integration no-cursor

#close force
confirm_os_window_close 0

#pywal(color)
include ~/.cache/wal/colors-kitty.conf