background {
    monitor =
    path = /home/zrin/Pictures/walls/cat.jpg  
    blur_passes = 1                  
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vignette = 0.0
    vignette_darkness = 0.0
}

input-field {
    monitor =
    size = 180, 30
    outline_thickness = 1
    dots_size = 0.25 # Ukuran titik password
    dots_spacing = 0.40 # Jarak antar titik
    dots_center = true
    outer_color = rgba(46, 117, 89, 0.6)       
    inner_color = rgba(20, 50, 40, 0.4)        
    font_color = rgb(220, 240, 230)
    fade_on_empty = false
    placeholder_text = <i></i>                 
    hide_input = false
    position = 0, -250                     
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H")"
    color = rgb(200, 240, 220)               
    font_size = 80
    font_family = JetBrains Mono Nerd Font Bold
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%M")"
    color = rgb(200, 240, 220)
    font_size = 80
    font_family = JetBrains Mono Nerd Font Bold
    position = 0, 70
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A")"
    color = rgb(170, 210, 190)
    font_size = 12
    font_family = JetBrains Mono Nerd Font
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%d %b")"
    color = rgb(170, 210, 190)
    font_size = 10
    font_family = JetBrains Mono Nerd Font
    position = 0, -35
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(/home/zrin/scripts/songdetail.sh)" 
    color = rgba(147, 196, 255, 1)
    font_size = 10
    font_family = JetBrains Mono Nerd, SF Pro Display Bold
    position = 0, 50
    halign = center
    valign = bottom
}